
data <- c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
mean_value <- mean(data)
median_value <- median(data)
mode_value <- as.numeric(names(table(data))[table(data) == max(table(data))])
data_range <- max(data) - min(data)
variance_value <- var(data)
std_deviation_value <- sd(data)
cat("Central Tendency Measures:\n")
cat("Mean:", mean_value, "\n")
cat("Median:", median_value, "\n")
cat("Mode:", mode_value, "\n\n")
cat("Data Dispersion Measures:\n")
cat("Range:", data_range, "\n")
cat("Variance:", variance_value, "\n")
cat("Standard Deviation:", std_deviation_value, "\n")
